apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bestcloud-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/abdullahozcalisan/bestcloud-deployment.git
    targetRevision: HEAD
    path: deploy
  destination: 
    server: https://kubernetes.default.svc
    namespace: bestcloudapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true  #otomatic sync
      prune: true